### PR TITLE
Increases RCL's capacity

### PR DESCRIPTION
**Pull request by MaltVinegar**
## About The Pull Request

fixes issue #83 by increasing the RCL's capacity to 900

## Changelog
:cl:
fix: increases the RCL's capacity to 900
/:cl:

### CODE REVIEW

**Review by Urumasi — APPROVED** [review]

**Comment by KubeRoot** [comment]
Should also increase makeshift RCL capacity

**Comment by MaltVinegar** [comment]
> 
> 
> Should also increase makeshift RCL capacity

fixed

**Review by KubeRoot — APPROVED** [review]
This might be the first time I witness bugfixing **through** buffing.

**Comment by MaltVinegar** [comment]
we do a little trolling

**Pull request merged**
