### PR TITLE
[Ready] Fixes ping display dying after a long time

### PR DESCRIPTION
**Pull request by Urumasi**
## About The Pull Request

After a long time, the client will start trying to call the .update_ping verb with scientific notation server time, breaking the syntax of `winset()`.
This fix encapsulates the number into a pair of quotes so it doesn't think the `+` in the scientific notation is supposed to be a space.

## Why It's Good For The Game

Seeing your ping is pretty nice :)

## Changelog
:cl: Urumasi
fix: Fixes ping becoming useless after really long round durations
/:cl:

### CODE REVIEW

**Review by MaltVinegar — APPROVED** [review]
I'll approve this so you can merge it whenever and it can get tested in-game, I'm not running an instance of SS13 for 24 hours on my laptop to test this.

**Comment by KubeRoot** [comment]
We can just testmerge this, no? All you have to do is convince Terra to press the right button...

**Comment by MaltVinegar** [comment]
> getting Terra to press buttons

**Comment by MaltVinegar** [comment]
Has this actually been Testmerged yet?

**Comment by Urumasi** [comment]
> 
> 
> Has this actually been Testmerged yet?

Yes, it's testmerged right now

**Comment by MaltVinegar** [comment]
Is it *actually* testmerged though

**Pull request merged**
