### PR TITLE
Constructionstation and cargo shuttle

### PR DESCRIPTION
**Pull request by MaltVinegar**
## About The Pull Request

Brings over the classic Constructionstation

## Why It's Good For The Game

Gotta have at least one map

## Changelog
:cl:
add: Constructionstation and its cargo shuttle
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
waga baga bobo

**Comment by Redory** [comment]
If you port over construction station then please fix the problems it currently has.
Namely:

[Hotwire of distro/waste under the DP vent](https://i.imgur.com/Xw8DDN1.png) (manifold is right next to it connecting it)
[Missing pipe segment under the door](https://i.imgur.com/8T1ht1n.png)
[Fucked up IDs for the loading doors and poddoors](https://i.imgur.com/NXb0Q09.png) (Pressing a button cross-opens the poddoors which shouldn't happen. Maybe even seperate IDs from shuttle/station since opening the poddoors on the station also opens them on the shuttle which might be in space and draining all the atmosphere of it. Also check conveyors i forgot to test em)
[Wrong usage of the airless tiles, air tiles](https://i.imgur.com/4PzST9y.png) (HEY! LISTEN! Airless in space fine, but air in spess makes byond scream at you)

Please fix terra's problems thank

**Comment by MaltVinegar** [comment]
I have fixed all of these but I would like to note that the first issue was my fault and issues with Cargo were Dakka's

**Comment by Tulenich** [comment]
You deleted boxstation? Won't it break everything?

**Comment by MaltVinegar** [comment]
> 
> 
> You deleted boxstation? Won't it break everything?

I fixed the thing that deleting boxstation broke

**Pull request merged**
