### PR TITLE
A brand new Construction Map A.K.A EtaStation!

### PR DESCRIPTION
**Pull request by Laboredih123**
## About The Pull Request

This PR will add a new construction map called EtaStation that will be bigger, shaped into a ~~U~~H, multi z hopefully, and *have a fucking disposals*.

## Why It's Good For The Game

A new map will allow us to add features we want, and to have something unique.

## Changelog
:cl:
add: Added a bigger, supposedly better, construction map !
/:cl:

### CODE REVIEW

**Comment by Laboredih123** [comment]
Will be waiting for approval whether to continue the map.

**Comment by Laboredih123** [comment]
just remembered the commits show up here lol, gonna start putting better descriptions

**Comment by Laboredih123** [comment]
I think that's good enough, Testmerge?

**Comment by Laboredih123** [comment]
Set to Ready and Review

**Comment by KubeRoot** [comment]
The PR contains a `_maps/map_files/ConstructionStationV2.1/ConstructionStationV2.1` file that probably shouldn't be there, what's up with that?

**Comment by Laboredih123** [comment]
> The PR contains a `_maps/map_files/ConstructionStationV2.1/ConstructionStationV2.1` file that probably shouldn't be there, what's up with that?

Something that's just in case people don't like this version of the map. It doesn't do anything rn.

**Comment by KubeRoot** [comment]
> Something that's just in case people don't like this version of the map. It doesn't do anything rn.

Why is it in the PR though? If it's an old version, you can always restore a previous commit using git. If it's an alternative version, shouldn't be in the PR, should either be out of the git repository or on another branch.

**Comment by Laboredih123** [comment]
I'll remove it

**Comment by Laboredih123** [comment]
i think we can test merge now, opinions?

**Comment by Laboredih123** [comment]
Pc taken away, pr on indefinite hiatus, contributions appreciated greatly

**Comment by Laboredih123** [comment]
SILENCE BOT

**Comment by Laboredih123** [comment]
there, now shut up "github-actions"

**Comment by Laboredih123** [comment]
mfw i forgot to add a cyborg recharging station:

**Comment by Laboredih123** [comment]
can someone add that? i cant since no pc

**Comment by Laboredih123** [comment]
got my pc for a bit, gonna try and fix a few things

**Comment by Laboredih123** [comment]
soon

**Comment by Laboredih123** [comment]
DONT MERGE YET BTW.

**Comment by Laboredih123** [comment]
IT WOULD BE FAIL IF THE STATION DEPRESSURIZED ON ROUND START. i need to implement the layouts for the top and bottom stations

**Comment by KubeRoot** [comment]
Reset the branch to an earlier state at Laboredih123's request

**Comment by Laboredih123** [comment]
Moving to SSB, closing pr

**Pull request closed without merging**
